config:
  # vali is unable to cope with IPv6, hence disable logging entirely
  logging:
    enabled: false
  seedConfig:
    spec:
      networks:
        ipFamilies:
        - IPv6
        nodes: fd00:10::/64
        # Those CIDRs must match those specified in the kind Cluster configuration.
        pods: fd00:10:1::/56
        services: fd00:10:2::/112
        shootDefaults:
          ipFamilies:
          - IPv6
          pods: fd00:10:3::/56
          services: fd00:10:4::/112

